---
title: "Grid plot of best fit flexible models"
subtitle: "Association between HLI and common cancer incidence in NOWAC"
author: "Sairah L.F. Chen"
date: "11/12/2020"
output: "pdf_document" 



# Do not knit
# RUN THIS TO RENDER: markdown::render("C:/Users/sch044/OneDrive - UiT Office 365/R/Paper1_new/r_docs/flexible_bestfit_plot.Rmd", output_format= "pdf_document", output_file = "C:/Users/sch044/OneDrive - UiT Office 365/R/Paper1_new/output/figure_2.pdf")
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rms)
library(survival)
library(tidyverse)
library(ggpubr)
library(cowplot)


casesIncluded <- read.csv2(file="../data/casesIncluded25112020.csv")
```
```{r, setup datadist, include=FALSE}
ddist <- datadist(casesIncluded)
options(datadist="ddist")
ddist$limits["Adjust to", "HLIScore"] <- 5
```



```{r best fit plots , echo=FALSE, warning=FALSE}


# breast, 3 knots
coxspline3Breast <- cph(Surv(ageMenopause, ageExit, statusBreast) ~ rcs(HLIScore, 3) + 
                          education +
                          height +
                          HRTStatus +
                          OCEverUse +
                          parityCat +
                          familyHistBC +
                          ageMenarche +
                          breastfeedingCat, data=casesIncluded, x=TRUE, y=TRUE)



plotBreast3 <- ggplot(rms:::Predict(coxspline3Breast, HLIScore=seq(1, 20), 
                                    ref.zero = TRUE,
                                    fun=exp),
                            xlab= "HLI Score",
                            ylab="HR",
                            adj.subtitle = FALSE) +
              geom_hline(yintercept=1, linetype="dashed") +
              ggtitle("Postmenopausal breast cancer") +
              theme(legend.position = "none")

#crc, 3 knots

coxspline3Colorectal <- cph(Surv(ageEntry, ageExit, statusColorectal) ~ 
                              rcs(HLIScore, 3) + 
                              education +
                              height, data=casesIncluded, x=TRUE, y=TRUE)

plotColorectal3 <- ggplot(rms:::Predict(coxspline3Colorectal, HLIScore=seq(1, 20),
                                        ref.zero = TRUE,
                                        fun=exp),
                            xlab= "HLI Score",
                            ylab="HR",
                            adj.subtitle = FALSE) + 
                    geom_hline(yintercept=1, linetype="dashed") +
                    ggtitle("Colorectal cancer")

#lung, 5 knots


coxspline3Lung <- cph(Surv(ageEntry, ageExit, statusLung) ~ 
                        rcs(HLIScore, 3) + 
                        education +
                        height, data=casesIncluded, x=TRUE, y=TRUE)
plotLung3 <- ggplot(rms:::Predict(coxspline3Lung, HLIScore=seq(1, 20),
                                  ref.zero = TRUE,
                                  fun=exp),
                          xlab= "HLI Score",
                          ylab="HR",
                          adj.subtitle = FALSE) + 
              geom_hline(yintercept=1, linetype="dashed") +
              ggtitle("Lung cancer")

# endometrial, 3 knots
coxspline3Endometrial <- cph(Surv(ageMenopause, ageExit, statusEndometrial) ~ rcs(HLIScore, 3) + 
                          education +
                          height +
                          HRTStatus +
                          OCEverUse +
                          parityCat +
                          ageMenarche +
                          breastfeedingCat, data=casesIncluded, x=TRUE, y=TRUE)

plotEndometrial3 <- ggplot(rms:::Predict(coxspline3Endometrial, HLIScore=seq(1, 20),
                                         ref.zero = TRUE,
                                         fun=exp),
                        xlab= "HLI Score",
                        ylab="HR",
                        adj.subtitle = FALSE) + 
                    geom_hline(yintercept=1, linetype="dashed") +
                    ggtitle("Postmenopausal endometrial cancer")


# ovarian, 3 knots
coxspline3Ovarian <- cph(Surv(ageMenopause, ageExit, statusOvarian) ~ rcs(HLIScore, 3) + 
                          education +
                          height +
                          HRTStatus +
                          OCEverUse +
                          parityCat +
                          ageMenarche +
                          breastfeedingCat, data=casesIncluded, x=TRUE, y=TRUE)

plotOvarian3 <- ggplot(rms:::Predict(coxspline3Ovarian, HLIScore=seq(1, 20),
                                     ref.zero = TRUE,
                                     fun=exp),
                        xlab= "HLI Score",
                        ylab="HR",
                        adj.subtitle = FALSE) + 
                geom_hline(yintercept=1, linetype="dashed") +
                ggtitle("Postmenopausal ovarian cancer")

# pancreatic, 3 knots
coxspline3Pancreatic <- cph(Surv(ageEntry, ageExit, statusPancreatic) ~ 
                              rcs(HLIScore, 3) + 
                              education +
                              height, data=casesIncluded, x=TRUE, y=TRUE)

plotPancreatic3 <- ggplot(rms:::Predict(coxspline3Pancreatic, HLIScore=seq(1, 20),
                                        ref.zero = TRUE,
                                        fun=exp),
                        xlab= "HLI Score",
                        ylab="HR",
                        adj.subtitle = FALSE) + 
                    geom_hline(yintercept=1, linetype="dashed") +
                    ggtitle("Pancreatic cancer")

# kidney, 3 knots

coxspline3Kidney <- cph(Surv(ageEntry, ageExit, statusKidney) ~ 
                          rcs(HLIScore, 3) + 
                          education +
                          height, data=casesIncluded, x=TRUE, y=TRUE)

plotKidney3 <- ggplot(rms:::Predict(coxspline3Kidney, HLIScore=seq(1, 20),
                                    ref.zero = TRUE,
                                    fun=exp),
                            xlab= "HLI Score",
                            ylab="HR",
                            adj.subtitle = FALSE) + 
                geom_hline(yintercept=1, linetype="dashed") +
                ggtitle("Kidney cancer")


plot <- plot_grid(plotBreast3, #need to label with a,b,c etc
             plotColorectal3, 
             plotLung3,
             plotEndometrial3,
             plotOvarian3,
             plotPancreatic3,
             plotKidney3,
             ncol=3, nrow=3,
             labels = c("a","b","c","d","e","f","g")) 



# save to png
png("C:/Users/sch044/OneDrive - UiT Office 365/R/Paper1_new/output/figure_2.png", width= 1000, height = 1000)
print(plot)
dev.off()

#flexiblePlot

```






