---
title: "linear forest plot for main article" 
subtitle: "Association between HLI and common cancer incidence in NOWAC"
author: "Sairah L.F. Chen"
date: "06/11/2020"


# Do not knit
# This document is for generating png (or other format) of forest plot for main article
---

```{r setup, include=FALSE}
library(ggplot2)
library(forestplot)
```

```{r ::forestplot, include=FALSE}

# create plot data object

forestPlotData <- 
  data.frame(
    coef = c(NA,0.97,0.98,0.86,0.93,0.99,0.92,0.94),
    low = c(NA,0.96,0.96,0.84,0.91,0.96,0.89,0.91),
    high = c(NA,0.98,1.00,0.87,0.95,1.02,0.95,0.97))


# create table text

tableText <- cbind(
  c("Cancer type",
    "Postmenopausal breast", 
    "Colorectal",
    "Lung",
    "Postmenopausal endometrial",
    "Postmenopausal ovarian",
    "Pancreatic",
    "Kidney"),
  c("N cases",
    "4286",
    "1281",
    "1097",
    "1043",
    "418",
    "300",
    "282"),
  c("HR (95% CI)",
    "0.97 (0.96-0.98)",
    "0.98 (0.96-1.00)",
    "0.86 (0.84-0.87)",
    "0.93 (0.91-0.95)",
    "0.99 (0.96-1.02)",
    "0.92 (0.89-0.95)",
    "0.94 (0.91-0.97)")
)

# set graphic element design
own <- fpTxtGp()
own # see parameters
own <- fpTxtGp(label=gpar(cex=0.75),
               xlab = gpar(cex=0.75)) # change tabletext font

# merge plot with table

png("C:/Users/sch044/OneDrive - UiT Office 365/R/Paper1_new/output/fig1.png", width=6.2, height=4, units="in", res = 300)

fp <- forestplot(tableText,
                 forestPlotData,
                 new_page = TRUE,
                 boxsize = 0.1,
                 is.summary = c(TRUE, rep(FALSE,7)), # forces first row of text table into summary element, making it bold
                 xlog=TRUE,
                 xticks = c(0.85,0.90,0.95,1.00,1.05),
                 grid=TRUE,
                 graphwidth = unit(5, "cm"),
                 txt_gp = own)
dev.off()


```



```{r forest plot ggplot, include=FALSE}
# old forest plot made in ggplot, does not include table like in ::forestplot

label <- c("Postmenopausal breast", 
           "Colorectal",
           "Lung",
           "Postmenopausal endometrial",
           "Postmenopausal ovarian",
           "Pancreatic",
           "Kidney")
estimate <- c(0.97,0.98,0.86,0.93,0.99,0.92,0.94)
lower_ci <- c(0.96,0.96,0.84,0.91,0.96,0.89,0.91)
upper_ci <- c(0.98,1.00,0.87,0.95,1.02,0.95,0.97)

df <- data.frame(label, estimate, lower_ci, upper_ci)

# reverses the factor level ordering for labels after coord_flip()
df$label <- factor(df$label, levels=rev(df$label))

fp <- ggplot(data=df, aes(x=label, y=estimate, ymin=lower_ci, ymax=upper_ci)) +
        geom_pointrange(color="blue", size=1) + 
        geom_errorbar(aes(ymin=lower_ci, ymax=upper_ci),width=0.1, size=1, color="blue")+
        theme(text = element_text(size=35))+
        geom_hline(yintercept=1, lty=2) +  # add a dotted line at x=1 after flip
        coord_flip() +# flip coordinates (puts labels on y axis)
        xlab("Cancer type") + ylab("HR (95% CI)")
        theme_bw()   # use a white background
    
labpos <- c(1.03)
labels <- c()
for (i in 1:7) {
  labels[i] = paste(sprintf("%.2f", estimate[i]), "(", sprintf("%.2f", lower_ci[i]), "-", sprintf("%.2f", upper_ci[i]), ")")
}
 # c("0.97(0.96-0.98)", "0.98(0.97-1.00", "0.86(0.85-")
        
fp_labels <- fp + geom_text(size=9, aes(y=labpos, label=labels, hjust=0)) 
fp_with_labels <- fp_labels+ylim(c(0.82,1.10))

# save to png
png("C:/Users/sch044/OneDrive - UiT Office 365/R/Paper1_new/output/figure_1_old.png", width=1600, height=1200)
fp_with_labels
dev.off()

#save to pdf
#pdf("C:/Users/sch044/OneDrive - UiT Office 365/R/Paper1_new/output/forest_plot.pdf", width=20, height=20)
#print(fp_with_labels)
#dev.off()


```

